[project]
name = "codigo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "scipy>=1.16.3",
]
